# Generated by Django 5.2.6 on 2025-09-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='generation_context',
            field=models.TextField(default=None, null=True),
        ),
    ]
